site_name: Pipeline Project
theme:
  name: "readthedocs"
plugins:
  - mkdocstrings
nav:
  - Pipeline Docs: index.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - reference.md
  - explanation.md